//! Context assembly engine.
//!
//! Resolves relevant knowledge + session summaries for a working directory
//! and assembles them into a structured context document suitable for
//! injection into Claude sessions.

use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::store::KnowledgeStore;

/// Assemble the full context document for a given working directory.
///
/// Returns the assembled text, or an empty string if no relevant knowledge exists.
pub fn assemble_context(store: &KnowledgeStore, working_dir: &str) -> Result<String> {
    let knowledge = store.resolve_for_dir(working_dir)?;
    let summaries = store.recent_summaries_for_dir(working_dir, 5)?;

    if knowledge.is_empty() && summaries.is_empty() {
        return Ok(String::new());
    }

    let mut out = String::with_capacity(4096);

    // Knowledge section
    if !knowledge.is_empty() {
        let global: Vec<_> = knowledge.iter().filter(|k| k.scope == "global").collect();
        let project: Vec<_> = knowledge.iter().filter(|k| k.scope != "global").collect();

        if !global.is_empty() {
            writeln!(out, "# Organization Knowledge\n")?;
            for entry in &global {
                writeln!(out, "## {}", entry.title)?;
                if !entry.tags.is_empty() {
                    writeln!(out, "_Tags: {}_\n", entry.tags)?;
                }
                writeln!(out, "{}\n", entry.content.trim())?;
                writeln!(out, "---\n")?;
            }
        }

        if !project.is_empty() {
            writeln!(out, "# Project Knowledge\n")?;
            for entry in &project {
                writeln!(out, "## {}", entry.title)?;
                if !entry.tags.is_empty() {
                    writeln!(out, "_Tags: {}_\n", entry.tags)?;
                }
                writeln!(out, "{}\n", entry.content.trim())?;
                writeln!(out, "---\n")?;
            }
        }
    }

    // Session history section
    if !summaries.is_empty() {
        writeln!(out, "# Recent Session History\n")?;
        writeln!(out, "The following are summaries from prior Claude sessions in this project.\n")?;

        for summary in &summaries {
            writeln!(out, "## Session: {} ({})", summary.session_name, summary.created_at)?;
            writeln!(out)?;
            if !summary.summary.is_empty() {
                writeln!(out, "**Summary:** {}\n", summary.summary)?;
            }
            if !summary.decisions.is_empty() {
                writeln!(out, "**Key Decisions:** {}\n", summary.decisions)?;
            }
            if !summary.unresolved.is_empty() {
                writeln!(out, "**Unresolved:** {}\n", summary.unresolved)?;
            }
            writeln!(out, "---\n")?;
        }
    }

    Ok(out)
}

/// Write the assembled context to a `.cmdctl-context.md` file in the working directory.
/// Returns the path written, or None if context was empty.
pub fn write_context_file(store: &KnowledgeStore, working_dir: &str) -> Result<Option<String>> {
    let context = assemble_context(store, working_dir)?;
    if context.is_empty() {
        return Ok(None);
    }

    let dir = match Path::new(working_dir).canonicalize() {
        Ok(d) if d.is_dir() => d,
        _ => return Ok(None),
    };

    // Cap assembled context size to prevent knowledge store abuse.
    const MAX_CONTEXT_BYTES: usize = 64 * 1024;
    let context = if context.len() > MAX_CONTEXT_BYTES {
        tracing::warn!(
            "Assembled context exceeds {}KB limit, truncating",
            MAX_CONTEXT_BYTES / 1024
        );
        context[..MAX_CONTEXT_BYTES].to_string()
    } else {
        context
    };

    let context_path = dir.join(".cmdctl-context.md");
    let full_content = format!(
        "<!-- Auto-generated by CMD-CTL. Do not edit manually. -->\n\
         <!-- This file provides context from your team's knowledge base. -->\n\n\
         {context}"
    );
    fs::write(&context_path, &full_content)?;

    let path_str = context_path.to_string_lossy().to_string();
    tracing::info!("Wrote context file: {}", path_str);

    // If a CLAUDE.md exists but doesn't reference the context file, suggest adding it.
    let claude_md = dir.join("CLAUDE.md");
    if claude_md.exists() {
        if let Ok(existing) = fs::read_to_string(&claude_md) {
            if !existing.contains("cmdctl-context") {
                tracing::info!(
                    "Tip: add 'See .cmdctl-context.md' to your CLAUDE.md to include \
                     team knowledge context"
                );
            }
        }
    }

    Ok(Some(path_str))
}

/// Remove the context file from a working directory (cleanup).
pub fn remove_context_file(working_dir: &str) -> Result<()> {
    let dir = match Path::new(working_dir).canonicalize() {
        Ok(d) => d,
        Err(_) => return Ok(()),
    };
    let path = dir.join(".cmdctl-context.md");
    if path.exists() {
        fs::remove_file(&path)?;
    }
    Ok(())
}
