//! Context assembly engine.
//!
//! Resolves relevant knowledge + session summaries for a working directory
//! and assembles them into a structured context document suitable for
//! injection into Claude sessions.

use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::store::KnowledgeStore;

/// Assemble the full context document for a given working directory.
///
/// Returns the assembled text, or an empty string if no relevant knowledge exists.
pub fn assemble_context(store: &KnowledgeStore, working_dir: &str) -> Result<String> {
    let knowledge = store.resolve_for_dir(working_dir)?;
    let summaries = store.recent_summaries_for_dir(working_dir, 5)?;

    if knowledge.is_empty() && summaries.is_empty() {
        return Ok(String::new());
    }

    let mut out = String::with_capacity(4096);

    // Knowledge section
    if !knowledge.is_empty() {
        let global: Vec<_> = knowledge.iter().filter(|k| k.scope == "global").collect();
        let project: Vec<_> = knowledge.iter().filter(|k| k.scope != "global").collect();

        if !global.is_empty() {
            writeln!(out, "# Organization Knowledge\n")?;
            for entry in &global {
                writeln!(out, "## {}", entry.title)?;
                if !entry.tags.is_empty() {
                    writeln!(out, "_Tags: {}_\n", entry.tags)?;
                }
                writeln!(out, "{}\n", entry.content.trim())?;
                writeln!(out, "---\n")?;
            }
        }

        if !project.is_empty() {
            writeln!(out, "# Project Knowledge\n")?;
            for entry in &project {
                writeln!(out, "## {}", entry.title)?;
                if !entry.tags.is_empty() {
                    writeln!(out, "_Tags: {}_\n", entry.tags)?;
                }
                writeln!(out, "{}\n", entry.content.trim())?;
                writeln!(out, "---\n")?;
            }
        }
    }

    // Session history section
    if !summaries.is_empty() {
        writeln!(out, "# Recent Session History\n")?;
        writeln!(out, "The following are summaries from prior Claude sessions in this project.\n")?;

        for summary in &summaries {
            writeln!(out, "## Session: {} ({})", summary.session_name, summary.created_at)?;
            writeln!(out)?;
            if !summary.summary.is_empty() {
                writeln!(out, "**Summary:** {}\n", summary.summary)?;
            }
            if !summary.decisions.is_empty() {
                writeln!(out, "**Key Decisions:** {}\n", summary.decisions)?;
            }
            if !summary.unresolved.is_empty() {
                writeln!(out, "**Unresolved:** {}\n", summary.unresolved)?;
            }
            writeln!(out, "---\n")?;
        }
    }

    Ok(out)
}

/// Write the assembled context to a `.cmdctl-context.md` file in the working directory.
/// Returns the path written, or None if context was empty.
pub fn write_context_file(store: &KnowledgeStore, working_dir: &str) -> Result<Option<String>> {
    let context = assemble_context(store, working_dir)?;
    if context.is_empty() {
        return Ok(None);
    }

    let dir = Path::new(working_dir);
    if !dir.is_dir() {
        return Ok(None);
    }

    let context_path = dir.join(".cmdctl-context.md");
    let full_content = format!(
        "<!-- Auto-generated by CMD-CTL. Do not edit manually. -->\n\
         <!-- This file provides context from your team's knowledge base. -->\n\n\
         {context}"
    );
    fs::write(&context_path, &full_content)?;

    // Ensure CLAUDE.md references the context file.
    ensure_claude_md_reference(dir)?;

    let path_str = context_path.to_string_lossy().to_string();
    tracing::info!("Wrote context file: {}", path_str);
    Ok(Some(path_str))
}

/// If a CLAUDE.md exists in the directory, ensure it includes a reference
/// to .cmdctl-context.md. If no CLAUDE.md exists, create a minimal one.
fn ensure_claude_md_reference(dir: &Path) -> Result<()> {
    let claude_md = dir.join("CLAUDE.md");
    let reference_line = "\n<!-- cmdctl:context -->\nSee .cmdctl-context.md for additional project context from your team's knowledge base.\n";

    if claude_md.exists() {
        let existing = fs::read_to_string(&claude_md)?;
        if !existing.contains("cmdctl:context") {
            let mut content = existing;
            content.push_str(reference_line);
            fs::write(&claude_md, content)?;
        }
    }
    // If no CLAUDE.md exists, don't create one — just rely on .cmdctl-context.md.
    // Claude Code reads all .md files when referenced, and we can inject via PTY fallback.

    Ok(())
}

/// Remove the context file from a working directory (cleanup).
pub fn remove_context_file(working_dir: &str) -> Result<()> {
    let path = Path::new(working_dir).join(".cmdctl-context.md");
    if path.exists() {
        fs::remove_file(&path)?;
    }
    Ok(())
}
